from .home import home
from .pythagoras import pythagoras
from .fibonacci_sequence import Fibonacci
from .prediction import post_regression
from .determinant_calculator import post_to_function
from .std_deviation import post_stddev
from .pythagorean_theorem import pythagorean_theorem
from .mean import post_mean
from .calc1 import calc1
from .factorial import factorial
from .square_root_finder import square_root
from .median import medianer
from .convert_to_radians import toRadians
