from .home import home
from .pythagoras import pythagoras
from .fibonacci_sequence import Fibonacci
from .square_number import square_number
from .determinant_calculator import post_to_function
from .std_deviation import post_stddev
from .pythagorean_theorem import pythagorean_theorem
from .mean import post_mean
from .calc1 import calc1
from .factorial import factorial
