from .home import home
from .std_deviation import get_stddev
from .pythagoras import pythagoras
from .fibonacci_sequence import Fibonacci
from .square_number import square_number
from .std_deviation import post_stddev
from .determinant_calculator import post_to_function
from .std_deviation import get_stddev
from .pythagorean_theorem import pythagorean_theorem
from .calculator import calc
